//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        public int IdTarjeta { get; set; }
        public int NoCuenta { get; set; }
        public int NoTarjeta { get; set; }
        public int Nip { get; set; }
        public int Saldo { get; set; }
        public int IdClientes { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
